import 'package:get/get.dart';

class LocalLanguage extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'hello':'Hello ',
          'khmer': 'Khmer',
          'english': 'English',
          'selectLanguage': 'Select Language',
          'home': 'Home',
          'category': 'Category',
          'order': 'Order',
          'order_success_msg': 'Your order has been placed successfully',
          'order_failed': 'Your order has been failed',
          'notification': 'Notification',
          'account': 'Account',
          'profile': 'Profiles',
          'skip': 'Skip',
          'welcome_title_1': 'Welcome to MyPhsar',
          'welcome_message_1':
              'Here Shopping is easy and fun with 50,000 products, exclusive deals, offers, and promotions.',
          'welcome_title_2': 'Easy and Secure Checkout',
          'welcome_message_2':
              'Enjoy safer & payments. We offer world famous four payment gateway for smooth and safe payment for you purchase.',
          'welcome_title_3': 'Fastest Delivery',
          'welcome_message_3':
              'Thousand of sellers are waiting for your order, place an order, get fast delivery, and enjoy your daily life.',
          'next': 'Next',
          'msg': 'Message',
          'search': 'Search...',
          'search_product': 'Search Product.',
          'search_result':'Search Result',
          'brand': 'Brand',
          'special': 'Special',
          'specification': "Specification",
          'top_selling': 'Top Selling',
          'top_seller': 'Top Seller',
          'new_arrival': 'New Arrival',
          'installments': 'Installments',
          'installment_tag': 'បង់រំលោះ',
          'your': "Your",
          'place_success_message': 'has been placed successfully',
          'place_failed_message': 'has been placed failed',
          'sorry': 'Sorry!',
          'all_product': 'All Products',
          'product': 'Product',
          'running': 'Running',
          'delivery': 'Delivery',
          'canceled': 'Canceled',
          'orders': 'Orders',
          'payment': 'Payment',
          'payment_status': 'Payment Status',
          'delivery_status': 'Delivery Status',
          'thank_you': 'Thank you!',
          'about_us': 'About us',
          'about_myphsar': 'About MyPhsar',
          'term_condition': 'Terms and Conditions',
          'privacy_policy': 'Privacy Policy',
          'app_version': 'App Version',
          'address': 'Address',
          'no_address_msg': 'Please add shipping address',
          'home_address': 'Home',
          'office': 'Office',
          'other': 'Other',
          'contact_name': 'Contact Name',
          'contact_number': 'Contact Number',
          'address_alert_message': 'Please fill in all address',
          'add_address': 'Add Address',
          'pick_location': 'ជ្រើសរើសទីតាំង',
          'add_other_address': 'Add other address',
          'address_type': 'Address Type',
          'invalid_email': 'Invalid email',
          'delete_success': 'Delete Successfully!',
          'delete': 'Delete',
          'id': 'ID: ',
          "update_title_message": "Update Available.",
          "update_body_message": "A new version is available. Please update.",
          'delete_account_msg': 'Are you sure you want to delete account?',
          'remove_address_field': 'Remove Address Failed',
          'date': 'Date: ',
          'price': 'Price: \$',
          'price1': 'Price',
          'detail': 'Detail',
          'order_detail': 'Order Detail',
          'product_detail': 'Product Detail',
          'installment_detail': 'Installments Detail',
          'outstanding_balance': 'Outstanding Balance',
          'installment_term': 'Installments Term',
          'installment_info': "Installments Information",
          'full_name': 'Full Name: ',
          'email': 'Email: ',
          'email1': 'Email',
          'age': 'Age: ',
          'age_no:': 'Age',
          'phone_number': 'Phone Number: ',
          'phone_number1': 'Phone Number',
          'enter_pone': 'Enter your phone number',
          'permanent_address': "Permanent Address",
          'job_position': 'Job Position: ',
          'job': 'Job',
          'job_type': 'Job Type',
          'salary': 'Salary: ',
          'salary1': 'Salary',
          'save': 'Save',
          'province_city': 'Province/City: ',
          'province_city1': 'Province/City',
          'select_p_c': 'Select Province/City',
          'select_job_type': 'Select Job Type',
          'occupation': 'Occupation: ',
          'id_info': 'ID Card Information',
          'id_detail': 'ID Card Detail',
          'id_num': 'ID Number',
          'id_passport': 'ID/Passport',
          'selfie_id': 'Selfie with ID/Passport',
          'take_photo_note':
              '• សូមត្រៀមផ្ទៀងផ្ទាត់ និងថតផ្ទៃមុខ \n• សូមកុំពាក់វែនតា  កុំពាក់ម៉ាស់ កុំពាក់មួក ឬសម្ភារះ តុបតែងណាដែលបិទបាំងផ្ទៃមុខ\n• សូមថតផ្ទៃមុខទាំងមូលដោយមានផ្ទៃខាងក្រោយខ្នងស្រឡះល្អ។',
          'dob': 'Date of Birth: ',
          'dob_no:': 'Date of Birth',
          'male': 'Male',
          'female': 'Female',
          'home_num': 'Home Number: ',
          'street_num': 'Street Number: ',
          'place_birth': 'Place of Birth: ',
          'id_photo': 'ID Card Photo',
          'monthly_schedule': 'Fixed Monthly Payment Schedule',
          'num': 'No_',
          'principal': "Principal",
          'interest': 'Interest',
          'amount': 'Amount Paid',
          'balance': 'Balance',
          'offers': 'Offers',
          'pwd': 'Password',
          'change': 'Change',
          'change_pwd': 'Change Password',
          'old_pwd': 'Old Password',
          'new_pwd': 'New Password',
          'confirm_pwd': "Confirm Password",
          'confirm': 'Confirm',
          'pwd_no_match_mes': 'Your password and confirmation password do not match',
          'update_pwd': 'Update Password',
          'delete_acc': 'Delete Account',
          'setting': 'Setting',
          'chat_support': 'Chat Support',
          'subject': 'Subject',
          'message': 'Message: ',
          'messing_hint': 'Message...',
          'you': 'You',
          'submitted': 'Submitted',
          'submit': 'Submit Installments',
          'submit_ticket': 'Submit Ticket',
          'submit_field': 'Submit failed',
          'issue_detail_hint': 'Write your issue in details',
          'send': 'Send',
          'website_problem': 'Website Problem',
          'partner_request': 'Partner Request',
          'complaint': 'Complaint',
          'info_inquiry': 'Info Inquiry',
          'support_ticket': 'Support Ticket',
          'support_center': 'Support Center',
          'support': 'Support',
          'select_your_category': 'Select your category',
          'update_success': 'Update Successfully',
          'update_failed': 'Update failed',
          'update': 'Update',
          'first_name': 'First Name',
          'last_name': 'Last Name',
          'user_name': 'User Name',
          'add_to_wishlist': 'Add to Wishlist',
          'add_to_cart': 'Add to Cart',
          'added_to_cart': 'Added to Cart',
          'delete_wishlist_failed': 'Delete Wishlist Failed',
          'wishlist': 'Wishlist',
          'wish': 'Wish',
          'delete_confirm_msg': 'Are you sure you want to delete?',
          'yes': 'Yes',
          'no': 'No',
          'vtc_bank': 'Vattanac Bank',
          'pay_with_vtc': 'Pay with Vattanac Bank App',
          'gender': 'Gender',
          'duration': 'Duration',
          'select_duration': 'Select Duration',
          'ref_person': 'Reference Person',
          'ref_name': 'Reference Name',
          'track_order': 'Tracking Order',
          'voucher': 'Voucher',
          'no_image_select': 'No image selected',
          'sing_in_continue': 'Sign in to continue',
          'email_phone': 'Email or Phone',
          'invalid_phone_msg': 'Invalid Phone Number/Email.',
          'sing_in': 'SIGN IN',
          'or': 'Or',
          'tap_star_rate': 'Tape a star to rate',
          'rate_msg': 'How accurate was the product description?',
          'rate_success_msg': 'Thank you for your review and rating.',
          'submit_feedback': 'Submit Feedback',
          'feedback': 'Feedback',
          'back': 'Back',
          'log_in_fb': 'Login with facebook',
          'forget_pwd': 'Forget Password?',
          'dont_have_acc': 'Don’t have an account?',
          'register': 'Register',
          'reorder': 'Reorder',
          'create_new_acc': 'Create a new account',
          'sign_up': 'SIGN UP',
          'sign_in': "Sign In",
          'please_enter': 'Please Enter: ',
          'no_internet_con': 'No Internet Connection',
          'connected': 'Connected',
          'section_lock_msg': 'This section is locked',
          'please_sign_try_again': 'Please sign in and try again',
          'cancel': 'Cancel',
          'cart': 'Cart',
          'total': 'Total',
          'no_address': 'No Address',
          'total_installment_duration': 'Total Installments Duration',
          'total_interest_rate': 'Total Interest Rate',
          'total_installment': 'Total Installments',
          'total_payable': 'Total Payable: ',
          'check_out': 'Check out',
          'color': 'Colors',
          'qty': 'Qty',
          'price_': 'Price: ',
          'choose_variant_msg': 'Please choose product variants',
          'choose_shipping_method': 'Please choose shipping method',
          'shipping_method': 'Shipping Methods',
          'all': 'All',
          'welcome_to': 'Welcome to',
          'chat_with_shop': '\n This is the direct chat with the shop',
          'shop': 'Shop',
          'shop_profile': 'Shop Profile',
          'apply': 'Apply',
          'subtotal': 'Subtotal',
          'total_price': 'Total Price',
          'delivery_fee': 'Delivery Fee',
          'dis': 'Discount',
          'tax': 'Tax',
          'coupon_voucher': 'Coupon & Voucher',
          'process_to_pay': 'Process to pay',
          'shipping_price': 'Shipping Price: ',
          'shipping_address': 'Shipping Address',
          'from_mps_to': 'From MyPhsar to: ',
          'est_delivery': 'Estimated Delivery: ',
          'choose_way_to_pay': 'Choose way to pay',
          'cash_delivery': 'Cash on delivery',
          'choose_address_type': 'Set label address as',
          'flash_deal': 'Flash Deal',
          'see_all': 'See All',
          'daily_deals': 'Daily Deals',
          'time_left': 'Time Left',
          'recomend_for_you': 'Recommend for you',
          'price_range': 'Price Range',
          'search_shop': 'Search Shops...',
          'search_for': 'Search For ',
          'not_found': 'Not Found',
          'down_payment': "Down Payment",
          'interest_rate': 'Interest Rate',
          'rate': 'Rate: ',
          'fee': 'Fee',
          'selected': 'Selected: ',
          'available_lender': "Available Lender",
          'contact': 'Contact',
          'place_of_birth': 'Place of Birth',
          'permanence_residential': 'Permanence Residential',
          'home_number': 'Home Number',
          'st_num': 'Street Number',
          'per_address': 'Permanence Address',
          'please_take_photo': 'Please take photo',
          'go_setting_msg': 'Go to Settings to enable camera access',
          'go_setting': 'Go to setting',
          'take_id_photo': 'Take Id Photo',
          'preview': 'Preview',
          'review': 'Reviews',
          'visit': 'Visit',
          'pay_table': 'Payment Table',
          'fill_your_info': 'Fill your information',
          'receipt': 'Receipt ',
          'less_detail': 'Less Detail',
          'relate_product': 'Related Product',
          'relate_shop': 'Related Shops',
          'relate_cat': 'Related Category',
          'more': 'More',
          'view_all_review': 'View All Review',
          'desc': 'Description',
          'otp_note': 'We sent you a verification code to your phone number: ',
          'error_otp_msg': "Didn't receive any code  ",
          'verify_otp':'Verify OTP Code',
          'resend': 'Resend',
          'sec': 'sec',
          'new': 'New',
          'new_product': 'New Products',
          'all_rate': 'All Rating',
          'items': 'Items',
          'tracking': 'Tracking',
          'order_placed': 'Order placed',
          'est_delivery': 'Estimate delivery: ',
          'packaging': 'Packaging',
          'in_transit': 'in transit',
          'drop_off': 'Drop-off',
          'error_payment': 'Error processing payment, Please try again',
          'empty_product': 'Empty Product.',
          'product_not_found': 'Product not found',
          'key_not_found': 'Can’t find that keyword',
          'empty_category': 'Empty Category.',
          'empty_running': 'Empty Running',
          'empty_deliver': 'Empty Deliver',
          'empty_failed': 'Empty Failed',
          'empty_address': 'Empty Address',
          'empty_offer': 'Empty Offer',
          'cart_empty': 'Empty Card',
          'empty_chat': 'Empty Chat',
          'empty_review': 'Empty Review',
          'empty_description': 'Empty Description',
          'empty_noti': 'Empty Notification',
          'empty_top_seller': 'Empty Top Seller',
          'empty_cat': 'Empty Category',
          'empty_support': 'Empty Support Ticket',
          'empty_wishlist': 'Empty Wishlist',
          'empty_tracking': 'Empty Tracking',
          'empty_installments': 'Empty Installments',
          'input':'Input ',
          'no_available_lender': 'No Available lender',
          'log_out': 'Log Out',
          'filter': 'Filter by',
          'error_msg': 'Something went wrong \nPlease try again',
          'error_response_msg': 'There’s an issue on our end',
          'error_response_msg_body': 'We’re looking into the problem. Try refreshing or restart the app',
          'login_error_msg': 'Invalid user information or password',
          'log_in_google': 'Login with Google',
          'log_in_apple': 'Login with Apple',
          'log_out_msg': 'Are you sure you want to log out?',
          'pwd_not_match_msg':'The passwords you entered do not match. Please ensure they are the same and try again.',
          'enter_password_msg':'Enter your password',
          'clear':'Clear',
          'start_price':'Start Price',
          'end_price':'End Price',
         'continue_shopping':'Continue Shopping',
          'send_receipt_to':'We have sent receipt to ',
          'order_completed': 'Order Completed',
          'my_order':'My Order',
  'support_text':'Have any questions? Reach directly to our ',
          'order_fail':'Order Failed'

        },
        'kh_KM': {
          'hello':'ជំរាបសួរ ',
          'khmer': 'ភាសាខ្មែរ',
          'english': 'ភាសាអង់គ្លេស',
          'selectLanguage': 'ជ្រើសរើសភាសា',
          'home': 'ទំព័រដើម',
          'category': 'ប្រភេទ',
          'order': 'បញ្ជាទិញ',
          'order_success_msg': 'ការបញ្ជាទិញរបស់អ្នកត្រូវបានដាក់ដោយជោគជ័យ',
          'order_failed': 'ការបញ្ជាទិញរបស់អ្នកត្រូវបានបរាជ័យ',
          'notification': 'ជូនដំណឹង',
          'account': 'គណនី',
          'profile': 'ប្រវត្តិរូប',
          'skip': 'រំលង',
          'welcome_title_1': 'សូមស្វាគមន៍មកកាន់ MyPhsar',
          'welcome_message_1':
              'នៅទីនេះការទិញទំនិញមានភាពងាយស្រួល និងរីករាយជាមួយនឹងផលិតផល 50,000 ការផ្តល់ជូនផ្តាច់មុខ ការផ្តល់ជូន និងការផ្សព្វផ្សាយ។',
          'welcome_title_2': 'ការទូទាត់ងាយស្រួល និងមានសុវត្ថិភាព',
          'welcome_message_2':
              'រីករាយជាមួយការបង់ប្រាក់ និងសុវត្ថិភាពជាងមុន។ យើងផ្តល់ជូននូវច្រកទូទាត់ក្នុងស្រុកសម្រាប់ការទូទាត់ដោយរលូន និងសុវត្ថិភាពសម្រាប់ការទិញរបស់អ្នក។',
          'welcome_title_3': 'ការដឹកជញ្ជូនលឿនបំផុត',
          'welcome_message_3':
              'អ្នកលក់រាប់ពាន់នាក់កំពុងរង់ចាំការបញ្ជាទិញរបស់អ្នក ធ្វើការបញ្ជាទិញ ទទួលបានការដឹកជញ្ជូនលឿន ហើយរីករាយនឹងជីវិតប្រចាំថ្ងៃរបស់អ្នក។',
          'next': 'បន្ទាប់',
          'msg': 'សារ',
          'search': 'ស្វែងរក...',
          'search_product': 'ស្វែងរកផលិតផល',
          'search_result':'លទ្ធផលស្វែងរក',
          'brand': 'ម៉ាក',
          'special': 'ពិសេស',
          'specification': "ការបញ្ជាក់",
          'top_selling': 'លក់ដាច់ជាងគេ',
          'top_seller': 'អ្នកលក់ដាច់',
          'new_arrival': 'មកដល់ថ្មី',
          'installments': 'បង់រំលោះ',
          'installment_tag': 'បង់រំលោះ',
          'your': "របស់អ្នក",
          'place_success_message': 'ត្រូវបានដាក់ដោយជោគជ័យ',
          'place_failed_message': 'ត្រូវបានដាក់បរាជ័យ',
          'sorry': 'សុំទោស!',
          'all_product': 'ផលិតផលទាំងអស់',
          'product': 'ផលិតផល',
          'running': 'ដំណើរការ',
          'delivery': 'ការដឹកជញ្ជូន',
          'canceled': 'បានលុបចោល',
          'orders': 'ការបញ្ជាទិញ',
          'payment': 'ការទូទាត់',
          'payment_status': 'ស្ថានភាពការទូទាត់',
          'delivery_status': 'ស្ថានភាពការដឹកជញ្ជូន',
          'thank_you': 'សូមអរគុណ!',
          'about_us': 'អំពីពួកយើង',
          'about_myphsar': 'អំពី MyPhsar',
          'term_condition': 'លក្ខខណ្ឌ',
          'privacy_policy': 'គោលការណ៍ភាពឯកជន',
          'app_version': 'កំណែកម្មវិធី',
          'address': 'អាស័យដ្ឋាន',
          'no_address_msg': 'សូមបន្ថែមអាសយដ្ឋានដឹកជញ្ជូន',
          'home_address': 'ផ្ទះ',
          'office': 'ការិយាល័យ',
          'other': 'ផ្សេងទៀត',
          'contact_name': 'ឈ្មោះទំនាក់ទំនង',
          'contact_number': 'លេខទំនាក់ទំនង',
          'address_alert_message': 'សូមបំពេញអាសយដ្ឋានទាំងអស់',
          'add_address': 'បន្ថែមអាសយដ្ឋាន',
          'pick_location': 'Pick Location',
          'add_other_address': 'បន្ថែមអាសយដ្ឋានផ្សេងទៀត',
          'address_type': 'ប្រភេទអាសយដ្ឋាន',
          'invalid_email': 'អ៊ីមែលមិនត្រឹមត្រូវ',
          'delete_success': 'លុបដោយជោគជ័យ!',
          'delete': 'លុប',
          'id': 'ID: ',
          "update_title_message": "អាចធ្វើបច្ចុប្បន្នភាព",
          "update_body_message": "កំណែថ្មីអាចរកបាន។ សូមធ្វើបច្ចុប្បន្នភាព។",
          'delete_account_msg': 'តើអ្នកប្រាកដថាចង់លុបគណនីមែនទេ?',
          'remove_address_field': 'លុបអាសយដ្ឋានបានបរាជ័យ',
          'date': 'កាលបរិច្ឆេទ: ',
          'price': 'តម្លៃ: \$',
          'price1': 'តម្លៃ',
          'detail': 'ព័ត៌មានលម្អិត',
          'order_detail': 'ព័ត៌មានលម្អិតការបញ្ជាទិញ',
          'product_detail': 'ព័ត៌មានអំពីផលិតផល',
          'installment_detail': 'ការបង់រំលោះលម្អិត',
          'outstanding_balance': 'សមតុល្យនៅសល់',
          'installment_term': 'រយៈពេលនៃការបង់រំលោះ',
          'installment_info': "ព័ត៌មានការបង់រំលោះ",
          'full_name': 'ឈ្មោះពេញ: ',
          'email': 'អ៊ីមែល: ',
          'email1': 'អ៊ីមែល',
          'age': 'អាយុ: ',
          'age_no:': 'អាយុ',
          'phone_number': 'លេខទូរសព្ទ: ',
          'phone_number1': 'លេខទូរសព្ទ',
          'enter_pone': 'បញ្ចូលលេខទូរស័ព្ទរបស់អ្នក',
          'permanent_address': "អាសយដ្ឋានអចិន្ត្រៃយ៍",
          'job_position': 'មុខតំណែងការងារ: ',
          'job': 'ការងារ',
          'job_type': 'ប្រភេទការងារ',
          'salary': 'ប្រាក់ខែ: ',
          'salary1': 'ប្រាក់ខែ',
          'save': 'រក្សាទុក',
          'province_city': 'ខេត្ត/ក្រុង: ',
          'province_city1': 'ខេត្ត/ក្រុង',
          'select_p_c': 'ជ្រើសរើសខេត្ត/ក្រុង',
          'select_job_type': 'ជ្រើសរើសប្រភេទការងារ',
          'occupation': 'មុខរបរ: ',
          'id_info': 'ព័ត៌មានអត្តសញ្ញាណប័ណ្ណ',
          'id_detail': 'ព័ត៌មានលម្អិតអំពីអត្តសញ្ញាណប័ណ្ណ',
          'id_num': 'លេខសម្គាល់: ',
          'id_passport': 'អត្តសញ្ញាណប័ណ្ណ/លិខិតឆ្លងដែន',
          'selfie_id': 'Selfie ជាមួយអត្តសញ្ញាណប័ណ្ណ/លិខិតឆ្លងដែន',
          'take_photo_note':
              '• សូមត្រៀមផ្ទៀងផ្ទាត់ និងថតផ្ទៃមុខ \n• សូមកុំពាក់វែនតា  កុំពាក់ម៉ាស់ កុំពាក់មួក ឬសម្ភារះ តុបតែងណាដែលបិទបាំងផ្ទៃមុខ\n• សូមថតផ្ទៃមុខទាំងមូលដោយមានផ្ទៃខាងក្រោយខ្នងស្រឡះល្អ។',
          'dob': 'ថ្ងៃខែឆ្នាំកំណើត: ',
          'dob_no:': 'ថ្ងៃខែឆ្នាំកំណើត',
          'male': 'ប្រុស',
          'female': 'ស្រី',
          'home_num': 'លេខផ្ទះ: ',
          'street_num': 'លេខផ្លូវ: ',
          'place_birth': 'ទីកន្លែងកំណើត: ',
          'id_photo': 'រូបថតអត្តសញ្ញាណប័ណ្ណ',
          'monthly_schedule': 'កាលវិភាគទូទាត់ថេរប្រចាំខែ',
          'num': 'ចំនួន',
          'principal': "ប្រាក់ដើម",
          'interest': 'ការប្រាក់',
          'amount': 'ចំនួនទឹកប្រាក់',
          'balance': 'សមតុល្យ',
          'offers': 'ការផ្តល់ជូន',
          'pwd': 'ពាក្យសម្ងាត់',
          'change': 'ផ្លាស់ប្តូរ',
          'change_pwd': 'ផ្លាស់ប្តូរពាក្យសម្ងាត់',
          'old_pwd': 'ពាក្យសម្ងាត់សំងាតចាស់',
          'new_pwd': 'ពាក្យសម្ងាត់ថ្មី',
          'confirm_pwd': "បញ្ជាក់ពាក្យសម្ងាត់",
          'confirm': 'បញ្ជាក់',
          'pwd_no_match_mes': 'ពាក្យសម្ងាត់ និងពាក្យសម្ងាត់បញ្ជាក់របស់អ្នកមិនត្រូវគ្នាទេ។',
          'update_pwd': 'ធ្វើបច្ចុប្បន្នភាពពាក្យសម្ងាត់',
          'delete_acc': 'លុបគណនី',
          'setting': 'ការកំណត់',
          'chat_support': 'ជជែកជាមួយជំនួយការ',
          'subject': 'ប្រធានបទ',
          'message': 'សារ: ',
          'messing_hint': 'សារ...',
          'you': 'អ្នក',
          'submitted': 'បានដាក់ស្នើ',
          'submit': 'ដាក់ស្នើបង់រំលោះ',
          'submit_ticket': 'ដាក់ស្នើសំបុត្រ',
          'submit_field': 'ការបញ្ជូនបរាជ័យ',
          'issue_detail_hint': 'សរសេរបញ្ហារបស់អ្នក',
          'send': 'ផ្ញើ',
          'website_problem': 'បញ្ហាគេហទំព័រ',
          'partner_request': 'សំណើដៃគូ',
          'complaint': 'ពាក្យបណ្តឹង',
          'info_inquiry': 'ការសាកសួរព័ត៌មាន',
          'support_ticket': 'សំបុត្រគាំទ្រ',
          'support_center': 'មជ្ឈមណ្ឌលគាំទ្រ',
          'support': 'គាំទ្រ',
          'select_your_category': 'ជ្រើសរើសប្រភេទរបស់អ្នក។',
          'update_success': 'ធ្វើបច្ចុប្បន្នភាពដោយជោគជ័យ',
          'update_failed': 'ការអាប់ដេតបានបរាជ័យ',
          'update': 'ធ្វើបច្ចុប្បន្នភាព',
          'first_name': 'នាមត្រកូល',
          'last_name': 'នាមខ្លួន',
          'user_name': 'ឈ្មោះអ្នកប្រើប្រាស់',
          'add_to_wishlist': 'ដាក់ចូលបញ្ជីពេញចិត្ត',
          'add_to_cart': 'ដាក់ចូលកន្ត្រក',
          'added_to_cart': 'បានដាក់ចូលកន្ត្រក',
          'delete_wishlist_failed': 'បរាជ័យក្នុងការលុបបញ្ជីពេញចិត្ត',
          'wishlist': 'បញ្ជីពេញចិត្ត',
          'wish': 'ពេញចិត្ត',
          'delete_confirm_msg': 'តើអ្នកប្រាកដថាចង់លុបវាទេ?',
          'yes': 'យល់ព្រម',
          'no': 'ទេ',
          'vtc_bank': 'ធនាគារ វឌ្ឍនៈ',
          'pay_with_vtc': 'ទូទាត់ជាមួយធនាគារ វឌ្ឍនៈ',
          'gender': 'ភេទ',
          'duration': 'រយៈពេល',
          'select_duration': 'ជ្រើសរើសរយៈពេល',
          'ref_person': 'សាក្សី',
          'ref_name': 'ឈ្មោះសាក្សី',
          'track_order': 'តាមដានការបញ្ជាទិញ',
          'voucher': 'ប័ណ្ណបញ្ចុះតម្លៃ',
          'no_image_select': 'មិនបានជ្រើសរើសរូបភាពទេ។',
          'sing_in_continue': 'ចូលគណនីដើម្បីបន្ត',
          'email_phone': 'ឬទូរស័ព្ទអ៊ីមែល',
          'invalid_phone_msg': 'លេខទូរស័ព្ទ/អ៊ីមែលមិនត្រឹមត្រូវ',
          'sing_in': 'ចូល',
          'or': 'ឬ',
          'tap_star_rate': 'ចុចផ្កាយដើម្បីវាយតម្លៃ',
          'rate_msg': 'តើការរៀបរាប់នៃផលិតផលបានភាពត្រឹមត្រូវហើយឬទេ?',
          'rate_success_msg': 'សូមអរគុណចំពោះការវាយតម្លៃរបស់អ្នក',
          'submit_feedback': 'បញ្ជូនមតិកែលម្អ',
          'feedback': 'មតិកែលម្អ',
          'back': 'ត្រឡប់',
          'log_in_fb': 'ចូលជាមួយហ្វេសប៊ុក',
          'forget_pwd': 'ភ្លេចពាក្យសម្ងាត់?',
          'dont_have_acc': 'មិនមានគណនីមែនទេ?',
          'register': 'ចុះឈ្មោះ',
          'reorder': 'បញ្ជាទិញឡើងវិញ',
          'create_new_acc': 'បង្កើតគណនីថ្មី',
          'sign_up': 'ចុះឈ្មោះ',
          'sign_in': "ចូល",
          'please_enter': 'សូមបញ្ចូល: ',
          'no_internet_con': 'គ្មានការភ្ជាប់អ៊ីនធឺណិត',
          'connected': 'បានភ្ជាប់',
          'section_lock_msg': 'ផ្នែកនេះត្រូវបានចាក់សោ',
          'please_sign_try_again': 'សូមចូល ហើយព្យាយាមម្តងទៀត',
          'cancel': 'បោះបង់',
          'cart': 'កន្ត្រក',
          'total': 'សរុប',
          'no_address': 'គ្មានអាសយដ្ឋាន',
          'total_installment_duration': 'រយៈពេលនៃការបង់រំលោះ',
          'total_interest_rate': 'អត្រាការប្រាក់សរុប',
          'total_installment': 'បង់រំលោះសរុប',
          'total_payable': 'សរុបដែលត្រូវបង់: ',
          'check_out': 'ពិនិត្យកាបញ្ជាទិញ',
          'color': 'ពណ៌',
          'qty': 'ចំនួន',
          'price_': 'តម្លៃ: ',
          'choose_variant_msg': 'សូមជ្រើសរើសវ៉ារ្យ៉ង់ផលិតផល',
          'choose_shipping_method': 'សូមជ្រើសរើសមធ្យោបាយដឹកជញ្ជូន',
          'shipping_method': 'មធ្យោបាយដឹកជញ្ជូន',
          'all': 'ទាំងអស់',
          'welcome_to': 'ស្វាគមន៍មកកាន់',
          'chat_with_shop': '\n នេះជាការជជែកផ្ទាល់ជាមួយហាង',
          'shop': 'ហាង',
          'shop_profile': 'ព័ត៌មានហាង',
          'apply': 'ស្នើ',
          'subtotal': 'សរុបរង',
          'total_price': 'តម្លៃសរុប',
          'delivery_fee': 'ថ្លៃដឹកជញ្ជូន',
          'dis': 'បញ្ចុះតម្លៃ',
          'tax': 'ពន្ធ',
          'coupon_voucher': 'គូប៉ុង & ប័ណ្ណទូទាត់',
          'process_to_pay': 'ដំណើរការបង់ប្រាក់',
          'shipping_price': 'តម្លៃដឹកជញ្ជូន: ',
          'shipping_address': 'អាសយដ្ឋានដឹកជញ្ជូន',
          'from_mps_to': 'ពី MyPhsar ទៅ: ',
          'est_delivery': 'ប៉ាន់ស្មានការដឹកជញ្ជូន: ',
          'choose_way_to_pay': 'ជ្រើសរើសវិធីបង់ប្រាក់',
          'cash_delivery': 'បង់ប្រាក់ពេលអីវ៉ាន់ទៅដល់',
          'choose_address_type': 'កំណត់ប្រភេទអាសយដ្ឋានជា',
          'flash_deal': 'Flash Deal',
          'see_all': 'មើលទាំងអស់',
          'daily_deals': 'Daily Deals',
          'time_left': 'ពេលវេលានៅសល់',
          'recomend_for_you': 'ណែនាំសម្រាប់អ្នក',
          'price_range': 'កម្រិតតម្លៃ',
          'search_shop': 'ស្វែងរកហាង...',
          'search_for': 'ស្វែងរក ',
          'not_found': 'រកមិនឃើញ',
          'down_payment': "លុយកក់",
          'interest_rate': 'អត្រាការប្រាក់',
          'rate': 'អត្រា: ',
          'fee': 'ថ្លៃសេវា',
          'selected': 'បានជ្រើសរើស: ',
          'available_lender': "អ្នកផ្តល់ប្រាក់កម្ចី",
          'contact': 'ទំនាក់ទំនង',
          'place_of_birth': 'ទីកន្លែងកំណើត',
          'permanence_residential': 'លំនៅដ្ឋានអចិន្រ្តៃយ៍',
          'home_number': 'លេខផ្ទះ',
          'st_num': 'លេខផ្លូវ',
          'per_address': 'អាសយដ្ឋានអចិន្ត្រៃយ៍',
          'please_take_photo': 'សូមថតរូប',
          'go_setting_msg': 'ចូលទៅកាន់ការកំណត់ដើម្បីបើកការចូលប្រើកាមេរ៉ា',
          'go_setting': 'ចូលទៅកាន់ការកំណត់',
          'take_id_photo': 'ថតរូបអត្តសញ្ញាណ',
          'preview': 'ពិនិត្យ',
          'review': 'ពិនិត្យ',
          'visit': 'ទៅកាន់',
          'pay_table': 'តារាងទូទាត់',
          'fill_your_info': 'បំពេញព័ត៌មានរបស់អ្នក',
          'receipt': 'បង្កាន់ដៃ ',
          'less_detail': 'ច្រើនទៀត',
          'relate_product': 'ផលិតផលស្រដៀងគ្នា',
          'relate_shop': 'ហាងដែលពាក់ព័ន្ធ',
          'relate_cat': 'ប្រភេទដែលពាក់ព័ន្ធ',
          'more': 'ច្រើនទៀត',
          'view_all_review': 'មើលការវាយតម្លៃទាំងអស់',
          'desc': 'ការពិពណ៌នា',
          'otp_note': 'យើងបានផ្ញើលេខកូដផ្ទៀងផ្ទាត់ទៅលេខទូរសព្ទរបស់អ្នក: ',
          'error_otp_msg': 'មិនបានទទួលលេខកូដមេនទេ  ',
          'verify_otp':'ផ្ទៀងផ្ទាត់លេខកូដ OTP',
          'resend': 'ផ្ញើឡើងវិញ',
          'sec': 'sec',
          'new': 'ថ្មី',
          'new_product': 'ផលិតផលថ្មី',
          'all_rate': 'ការវាយតម្លៃទាំងអស់',
          'items': 'ធាតុ',
          'tracking': 'ការតាមដាន',
          'order_placed': 'ការបញ្ជាទិញត្រូវបានដាក់',
          'est_delivery': 'ប៉ាន់ស្មានការដឹកជញ្ជូន',
          'packaging': 'កំពុងវេចខ្ចប់',
          'in_transit': 'ដឹកចេញ',
          'drop_off': 'ដឹកទៅដល់',
          'error_payment': 'កំហុសក្នុងដំណើរការការទូទាត់ សូមព្យាយាមម្តងទៀត',
          'empty_product': 'មិនមានផលិតផល.',
          'product_not_found': 'រកមិនឃើញផលិតផល',
          'key_not_found': 'រកមិនឃើញផលិតផល',
          'empty_category': 'មិនមានប្រភេទ.',
          'empty_running': 'មិនមានដំណើរការ',
          'empty_deliver': 'មិនមានបានទិញ',
          'empty_failed': 'មិនមានបរាជ័យ',
          'empty_address': 'មិនមានអាស័យដ្ឋាន',
          'empty_offer': 'មិនមានការផ្តល់ជូន',
          'cart_empty': 'មិនមានក្នុងកន្ត្រក',
          'empty_chat': 'មិនមានកាជជែក',
          'empty_review': 'មិនមានពិនិត្យឡើងវិញ',
          'empty_description': 'មិនមានការពិពណ៌នា',
          'empty_noti': 'មិនមានជូនដំណឹង',
          'empty_top_seller': 'មិនមានអ្នកលក់ដាច់',
          'empty_cat': 'មិនមានប្រភេទ',
          'empty_support': 'មិនមានសំបុត្រគាំទ្រ',
          'empty_wishlist': 'មិនមានបញ្ជីពេញចិត្ត',
          'empty_tracking': 'មិនមានការតាមដាន',
          'empty_installments': 'មិនមានការបង់រំលោះ',
          'input':'បញ្ចូល',
          'no_available_lender': 'មិនមានអ្នកផ្តល់ប្រាក់កម្ចី',
          'log_out': 'ចាកចេញ',
          'filter': 'តម្រងដោយ',
          'error_msg': 'មានអ្វីមួយខុសប្រក្រតី \nសូមព្យាយាមម្តងទៀត',
          'error_response_msg': 'មានបញ្ហានៅម៉ាស៊ីនរបស់យើង',
          'error_response_msg_body': 'យើងកំពុងពិនិត្យមើលបញ្ហា។ សាកល្បងផ្ទុកឡើងវិញ ឬចាប់ផ្តើមកម្មវិធីឡើងវិញ',
          'login_error_msg': 'ព័ត៌មានអ្នកប្រើ ឬពាក្យសម្ងាត់មិនត្រឹមត្រូវ',
          'log_in_google': 'Login with Google',
          'log_in_apple': 'Login with Apple',
          'log_out_msg': 'តើអ្នកពិតជាចង់ចាកចេញមែនទេ?',
          'pwd_not_match_msg':'ពាក្យសម្ងាត់ដែលអ្នកបានបញ្ចូលមិនត្រូវគ្នាទេ។ សូមប្រាកដថាពួកវាដូចគ្នា ហើយព្យាយាមម្តងទៀត។',
          'enter_password_msg':'បញ្ចូលពាក្យសម្ងាត់របស់អ្នក',
          'clear':'ជម្រះ',
          'start_price':'តម្លៃចាប់ផ្តើម',
          'end_price':'តម្លៃបញ្ចប់',
          'continue_shopping':'បន្តទិញទំនិញ',
          'send_receipt_to':'យើងបានផ្ញើបង្កាន់ដៃទៅ ',
          'order_completed': 'ការបញ្ជាទិញបានបញ្ចប់',
          'my_order':'ការបញ្ជាទិញរបស់ខ្ញុំ',
          'support_text':'មានសំណួរ? ទំនាក់ទំនងមកកាន់យើងខ្ញុំដោយផ្ទាល់ ',
          'order_fail':'ការបញ្ជាទិញបរាជ័យ'

        }
      };
}
